### PR TITLE
Use the Async DNS resolver where possible. Closes #543.

### LINKED ISSUE #543: Cannot close s3fs files during interpreter shutdown
This issue is really annoying and I'm not sure if it's an issue with s3fs, aiobotocore or aiohttp. The `S3File` is absolutely amazing, and one use case is with a Python logging `FileHandler` to stream log messages to S3. This works really well unless something closes the interpreter and forces the logging `atexit` handler to run. This causes `.close()` to explode because it ends up making `aiohttp` try to spawn a thread to resolve the S3 endpoint which isn't allowed during an interpreter shutdown.

Basically, the following code fails and that's a real shame:

```python
In [1]: import s3fs, atexit

In [2]: fs = s3fs.S3FileSystem()

In [6]: fd = fs.open("s3://foo/bar", "wb", bufsize=1024*1024*5)

In [7]: fd.write(b'Lol')
Out[7]: 3

In [8]: atexit.register(lambda: fd.close())
Out[8]: <function __main__.<lambda>()>

In [9]: exit()
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/s3fs/core.py", line 268, in _call_s3
    raise err
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/s3fs/core.py", line 248, in _call_s3
    out = await method(**additional_kwargs)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/client.py", line 141, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/client.py", line 161, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 81, in _send_request
    while await self._needs_retry(attempts, operation_model,
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 214, in _needs_retry
    responses = await self._event_emitter.emit(
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 148, in _do_get_response
    http_response = await self._send(request)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 230, in _send
    return await self.http_session.send(request)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 155, in send
    resp = await self._session.request(
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/tom/Library/Caches/pypoetry/virtualenvs/foo-nQOGymRb-py3.9/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 161, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

### PR DESCRIPTION
**Pull request by orf**
Needs https://github.com/aio-libs/aiobotocore/pull/906 first. I'll add tests once that's merged.

### CODE REVIEW

**Comment by martindurant** [comment]
Why is this not default? :)

**Comment by orf** [comment]
It needs an extra package installed I guess.

**Comment by isidentical** [comment]
> It needs an extra package installed I guess. I'm not really sure

If this is a third party dependency, wouldn't it make sense to ask clients to pass it instead of embedding it directly into s3fs? AFAIK you should be able to customize `config_kwargs`.

**Comment by orf** [comment]
Sure, but if you look at #543 there is a very annoying case where this is basically required.

If you use s3fs with the logging module then during interpreter shutdown it's more than likely that the files just won't be closed correctly.

So I feel like the aiodns resolver should be the default if it's available.

**Pull request closed without merging**
