### PR TITLE
fix bugs in _get_file

### PR DESCRIPTION
**Pull request by troychiu**
I fix some bugs in _get_file.

### CODE REVIEW

**Comment by martindurant** [comment]
Did you have some specific problems that led to this PR? The req_kw change looks right, but I am uncertain about the Range. Do you think tests can be made?

**Comment by troychiu** [comment]
I would love to write some test to validate this pr, but I am having trouble in how to simulate the fail of getting files. Do you have any idea?

**Comment by martindurant** [comment]
Perhaps if you detail how you noticed the bug, we could go from there? Did you have a specific workflow that went wrong?

**Comment by troychiu** [comment]
I found the bug when I was tracing the implementation, so there is not specific workflow that trigger the bug. I have done some research on simulating the error, but didn't find a effective way.

**Comment by troychiu** [comment]
If we merge this section of code and meet any problem, I will spend time looking into them.
But I am also fine with deleting it.

**Comment by martindurant** [comment]
I have convinced myself that the coe here is correct, and we can think about how to maybe test in a follow up

**Comment by troychiu** [comment]
I agree with you that the tests should be done.

**Comment by LukasBommes** [comment]
I can confirm the correctness of the fixes in thir PR. We spend the entire day debugging a problem related to this. Due to hitting [this bug in aiohttp](https://github.com/aio-libs/aiohttp/issues/4581) during `body.read` (in rare cases) the exception block was entered and here we noticed that upon retry the stream was read from the beginning instead of from the last byte read up to the exception. We fixed the issue exactly like in this PR. Obviously, we were on an older version of s3fs (2023.9.2) prior to this fix.

**Pull request merged**
