### PR TITLE
support callbacks in _get_file and _put_file

### PR DESCRIPTION
**Pull request by ap--**
Hello everyone,

This PR adds the callback keyword argument for both `_get_file` and `_put_file`.
See issue #589

Cheers,
Andreas 😃

### CODE REVIEW

**Comment by martindurant** [comment]
fsspec testing has a simple callback you can use to make sure that things work as they should

**Comment by martindurant** [comment]
(@isidentical , maybe you could suggest a simple way to test the callbacks)

**Comment by ap--** [comment]
Hi @martindurant 

Thanks for the feedback and the right pointer.
And sorry for the delay, it's been a busy day at work.
I'll push a test soon.

Cheers,
Andreas 😃

**Comment by martindurant** [comment]
Looks like `black` updated and started to reformat things. Please update your local version of `black` to get the formatting as required in CI, or else we could pin the version being used to do the check.

**Comment by ap--** [comment]
I added tests for `_get_file`, `_put_file` and the branching behaviour via `get` and `put`.

There's some inconsistencies regarding the callback call interface in `fsspec.asyn`.
Is `lazy_call` still supposed to be used?
It's not part of the `Callback` base class.

Should I open another issue for that in the filesystem_spec repository?

Cheers,
Andreas

**Comment by martindurant** [comment]
> Should the changes due to the new release of black be included in the main branch first and I rebase my changes on top?

That would make sense, but then you would have to wait around for someone to  do it, so maybe it's easier to do it here.

**Comment by martindurant** [comment]
Thank you

**Pull request merged**
