### PR TITLE
Set default cache type to "readahead"

### PR DESCRIPTION
**Pull request by mrocklin**
See analysis by @sneha5gsm in https://github.com/fsspec/s3fs/issues/677

### CODE REVIEW

**Comment by martindurant** [comment]
Breaks one specific test relying on the previous default value of the cache. Could pass "bytes" to the open() call to make it the same test as before, or alter the test. I can do it if you don't have time.

**Comment by mrocklin** [comment]
Oops, I screwed up my local git config and accidentally pushed this to the main fork.  My apologies.

**Comment by mrocklin** [comment]
Force pushed.  Looks like it's coming up green.  Thanks for the suggestion @martindurant

**Comment by martindurant** [comment]
(please delete the branch when you are done with it)

**Comment by mrocklin** [comment]
Done.  Again, my apologies.  

Thanks for merging!

Thanks also to @sneha5gsm whose work this really is.

**Pull request merged**
