### PR TITLE
Use read the docs v2 config

### PR DESCRIPTION
**Pull request by ianthomas23**
Second attempt at using RTD v2 config, auto building on RTD site.

### CODE REVIEW

**Comment by martindurant** [comment]
I don't see a new build on the s3fs dashboard of RTD

**Comment by martindurant** [comment]
Screen Shot 2023-02-01 at 10 44 12

**Comment by ianthomas23** [comment]
A bit of googling says that "resyncing the webhooks" might help. I don't know from which end (github, RTD) this can be done. Maybe both?

**Comment by martindurant** [comment]
Try again now? I also clicked a "PR" button in the github webhook config. I think it will now kick off a build, but I still need to find [this setting](https://docs.readthedocs.io/en/stable/pull-requests.html#privacy-levels) for the thing to get reported.

**Comment by martindurant** [comment]
(nvm, privacy is off by default for "free" use)

**Comment by martindurant** [comment]
I also re-added the RTD oauth to my github account, which should be enough for RTD to report back.

**Comment by martindurant** [comment]
This is good to go?

**Comment by ianthomas23** [comment]
Not quite, there are some warnings I'd like to deal with whilst this is all fresh in my mind. I'll ping you when it is ready.

**Comment by ianthomas23** [comment]
This is good to go now. Rendered output is here: https://s3fs--697.org.readthedocs.build/en/697/index.html

Summary of changes:

1. Fixes spaces between attribute names and types (fixes #269).
2. Fixes display of bullets points in changelog.
3. Updates RTD build system to give better control over version of python and dependencies, solution follows that of `fsspec`.
4. Treats all warnings as errors causing the doc build to fail, so we can't ignore warnings from now on.
5. Fixes a few minor warnings.
6. Switches from using `numpydoc` to `sphinx.ext.napoleon` which accepts `numpydoc`-style docstrings and also correctly deals with class members inherited from base classes in `fsspec`.

**Pull request merged**
