### PR TITLE
add skip_instance_cache kwargs to super_kwargs

### PR DESCRIPTION
**Pull request by jinmel**
Seems like skip_instance_cache is missing from super_kwargs :)

### CODE REVIEW

**Review by isidentical — APPROVED** [review]

**Comment by jinmel** [comment]
can you run the workflow? @isidentical

**Comment by isidentical** [comment]
Sure thing!

**Comment by martindurant** [comment]
Although this change should not break anything, it will have no effect, because `skip_instance_class` is swallowed by the metaclass on [this line](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/spec.py#L61) and should never appear in the kwargs. Did you have a case where the kwarg was causing a problem?

**Comment by jinmel** [comment]
@martindurant do you mean that this change is not necessary? I'll close this PR if so

+ Is metaclass instantiated before any class constructor?

**Comment by martindurant** [comment]
>  do you mean that this change is not necessary?

Correct, unless you have some specific case I haven't thought of showing a problem.

> Is metaclass instantiated before any class constructor

Sort of. Specifically, the metaclass's `__call__` method is used to create the new instance. In the case that we use a cached instance, `__init__` isn't called *at all*.

**Comment by jinmel** [comment]
Seems like the skip_instance_cache is working without this change. I am closing this PR. 

@martindurant thanks for your insight 😄

**Pull request closed without merging**
